# Generated by Django 4.2.6 on 2023-10-31 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('fecha_nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=70)),
                ('premios', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('apto_para_todos', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('fecha_estreno', models.DateField()),
                ('duracion', models.IntegerField()),
                ('recomendacionEdad', models.IntegerField()),
                ('vecesVista', models.IntegerField()),
                ('director', models.ManyToManyField(to='appDeustoFlix.director')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDeustoFlix.genero')),
            ],
        ),
    ]
