# Generated by Django 4.2.6 on 2023-11-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDeustoFlix', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='premios',
        ),
        migrations.AddField(
            model_name='director',
            name='premiado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='genero',
            name='apto_para_todos',
            field=models.BooleanField(default=False),
        ),
    ]
