# Generated by Django 4.2.6 on 2023-11-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDeustoFlix', '0002_remove_director_premios_director_premiado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Image'),
        ),
    ]
