# Generated by Django 4.2.7 on 2023-12-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDeustoFlix', '0004_director_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='calificacion',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='nombre_usuario',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='reseña',
            field=models.TextField(blank=True),
        ),
    ]
