# Generated by Django 4.2.7 on 2023-12-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDeustoFlix', '0005_pelicula_calificacion_pelicula_nombre_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='cantidad_calificaciones',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='total_calificaciones',
            field=models.FloatField(default=0),
        ),
    ]
