# Generated by Django 4.2.7 on 2023-12-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDeustoFlix', '0006_pelicula_cantidad_calificaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
