# Generated by Django 4.2.7 on 2023-12-08 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appDeustoFlix', '0007_pelicula_correo_electronico_pelicula_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='cantidad_calificaciones',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='calificacion_media',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='total_calificaciones',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.FloatField()),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('reseña', models.TextField(blank=True, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_pelicula', to='appDeustoFlix.pelicula')),
            ],
        ),
        migrations.AddField(
            model_name='pelicula',
            name='calificaciones',
            field=models.ManyToManyField(related_name='peliculas', to='appDeustoFlix.calificacion'),
        ),
    ]
